# Generated by Django 3.2.2 on 2021-05-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='treatment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
