# Generated by Django 3.2.3 on 2021-06-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_auto_20210614_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Rating',
        ),
    ]
