# Generated by Django 3.2.3 on 2021-06-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0004_rename_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.treatment'),
        ),
    ]
