# Generated by Django 3.2.3 on 2021-06-20 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatments', '0005_rating_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Average'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], default=3),
        ),
        migrations.AddField(
            model_name='rating',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
