# Generated by Django 3.2.3 on 2021-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0008_auto_20210625_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
