# Generated by Django 3.2.3 on 2021-06-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0009_alter_treatment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
