# Generated by Django 3.2.3 on 2021-06-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0011_remove_treatment_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treatment',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
