# Generated by Django 3.2.3 on 2021-06-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0012_auto_20210627_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='minutes',
        ),
    ]
