# Generated by Django 3.2.3 on 2021-06-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0014_offerspackagescategory_offerspackagestreatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerspackagescategory',
            options={'verbose_name_plural': 'Offers_Packages_Categories'},
        ),
    ]
