# Generated by Django 3.2.3 on 2021-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0015_alter_offerspackagescategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerspackagestreatment',
            name='offers_packages_category',
        ),
        migrations.AddField(
            model_name='treatment',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treatment',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OffersPackagesCategory',
        ),
        migrations.DeleteModel(
            name='OffersPackagesTreatment',
        ),
    ]
