# Generated by Django 3.2.3 on 2021-06-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0016_auto_20210628_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
