# Generated by Django 3.2.3 on 2021-06-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0018_auto_20210629_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='length_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treatment',
            name='length_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
