# Generated by Django 3.2.3 on 2021-06-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0019_auto_20210630_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='length_hours',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='length_minutes',
        ),
    ]
